stages:
  - test
  - deploy

test:
  stage: test
  interruptible: true
  tags:
    - KM-Medias
  image: axelterizaki/karaokemugen-ci:node-18
  script:
    - git clone https://gitlab.com/karaokemugen/code/karaokemugen-app.git
    - cd karaokemugen-app
    - yarn pull
    - yarn install
    - touch mpv    
    - touch patch
    - mkdir app
    - cp -f ../tools/config.CICD.yml app/config.yml
    - yarn ts-node util/extUnaccent
    - node -v
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
    - yarn startHeadless --verbose --validate --strict
  only:
    - master

export:
  stage: deploy
  image: curlimages/curl
  interruptible: true
  tags: 
    - $RUNNER_LINUX
  script:
    - echo "Triggering KM Server generation"
    - "curl -f -X POST -H authorization:$KMSERVERAUTH https://kara.moe/api/update"
    - "curl -f -X POST -H authorization:$KMSERVERDEVAUTH https://dev.kara.moe/api/update"
  only:
    - master
