stages:
  - test
  - deploy

test:
  stage: test
  interruptible: true
  tags:
    - KM-Medias
  image: axelterizaki/karaokemugen-ci:node-22
  script:
    - git clone --recurse-submodules https://gitlab.com/karaokemugen/code/karaokemugen-app.git
    - cd karaokemugen-app
    - yarn install
    - touch mpv
    - touch patch
    - mkdir app
    - cp -f ../config.CICD.yml app/config.yml
    - node -v
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
    - yarn startHeadless --verbose --validate --strict
  only:
    - master

i18nUpdate:
  stage: deploy
  image: curlimages/curl
  interruptible: true
  script:
    - curl -X POST -F "variables[FROM_BASE]=true" -F "token=$TRIGGER_I18N_TOKEN" -F "ref=main" "https://gitlab.com/api/v4/projects/59172300/trigger/pipeline"
  rules:
    - if: $CI_COMMIT_BRANCH != 'master'
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /^Update tags translations/'
      when: never
    - changes:
      - tags/*.tag.json
    - when: never

export:
  stage: deploy
  image: curlimages/curl
  interruptible: true
  script:
    - "curl -f -X POST -H authorization:$KMSERVERAUTH https://kara.moe/api/update"
  only:
    - master
