stages:
  - test
  - deploy

test:
  stage: test
  interruptible: true
  tags:
    - KM-Medias
  image: axelterizaki/karaokemugen-ci:node-16-phppg
  services:
    - postgres:13
  variables:
    POSTGRES_USER: karaokemugen_app
    POSTGRES_PASSWORD: musubi
  artifacts:
    expire_in: 1 day
    name: names.php
    paths:
      - names.php
      - searchbase.php
  script:
    - git clone https://gitlab.com/karaokemugen/karaokemugen-app.git
    - cd karaokemugen-app
    - yarn pull
    - yarn install
    - touch mpv    
    - mkdir app
    - cp -f ../tools/config.CICD.yml app/config.yml
    - yarn ts-node util/extUnaccent
    - node -v
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
    - yarn startHeadless --verbose --generate --strict
    - cd ..
    - php -d display_errors=stderr -d memory_limit=1G -f tools/export_karaokesmoe.php
  only:
    - master

export:
  stage: deploy
  image: axelterizaki/karaokemugen-ci:transferts
  interruptible: true
  script:
    - lftp -c "set cmd:fail-exit yes; set ftp:ssl-allow no; set ftp:charset "UTF-8" ; set file:charset utf-8; open -u $USERNAME,$PASSWORD $HOST; cd www/live.karaokes.moe; put names.php; put searchbase.php"
    - echo "Triggering KM Server generation"
    - "curl -f -X POST -H authorization:$KMSERVERAUTH https://kara.moe/api/update"
    - "curl -f -X POST -H authorization:$KMSERVERDEVAUTH https://dev.kara.moe/api/update"
  only:
    - master
